import type { DeckWord } from './deck';

/**
 * CURATED SENSE OVERRIDES — the enrichment pipeline picked WordNet's first
 * synset, which for many everyday nouns is a famous PERSON ("stone" ->
 * "United States architect (1902-1978)"). The observer recalls faithfully,
 * so a wrong sense becomes a confidently wrong answer. This layer replaces
 * the worst offenders with their common sense, written as noun phrases so
 * the relation extractor can read is-a edges from them. Also corrects stale
 * facts (the deck still taught nine planets).
 */
export const DEFINITION_OVERRIDES: ReadonlyMap<string, { definition: string; example: string }> = new Map([
  ['page', { definition: 'a single side of a sheet of paper in a book, magazine, or newspaper', example: 'Turn to the next page.' }],
  ['pages', { definition: 'the sides of sheets of paper in a book, magazine, or newspaper', example: 'The book has many pages.' }],
  ['service', { definition: 'an act of helpful work done for someone else', example: 'The hotel offers room service.' }],
  ['price', { definition: 'the amount of money needed to buy something', example: 'The price of bread went up.' }],
  ['prices', { definition: 'the amounts of money needed to buy things', example: 'Prices are higher this year.' }],
  ['day', { definition: 'a period of twenty-four hours, from one midnight to the next', example: 'The trip takes one day.' }],
  ['post', { definition: 'the system for delivering letters and packages; the mail', example: 'The letter came in the post.' }],
  ['posts', { definition: 'upright poles fixed into the ground', example: 'The fence posts are made of wood.' }],
  ['park', { definition: 'a large public area of grass and trees where people relax and play', example: 'The children play in the park.' }],
  ['key', { definition: 'a small shaped piece of metal used to open a lock', example: 'I lost my house key.' }],
  ['land', { definition: 'the solid dry part of the surface of the earth', example: 'The sailors saw land at last.' }],
  ['kids', { definition: 'young children', example: 'The kids are playing outside.' }],
  ['rock', { definition: 'a large mass of hard stone', example: 'The ship hit a rock.' }],
  ['town', { definition: 'a populated area with houses and shops, smaller than a city', example: 'She lives in a small town.' }],
  ['king', { definition: 'a male ruler of a country who inherits his position', example: 'The king lived in a castle.' }],
  ['cash', { definition: 'money in the form of coins and bills', example: 'He paid in cash.' }],
  ['hope', { definition: 'a feeling of wanting something to happen and believing it is possible', example: 'She never gave up hope.' }],
  ['tree', { definition: 'a tall plant with branches and a trunk of wood', example: 'The bird sat in the tree.' }],
  ['wood', { definition: 'the hard material that forms the trunk and branches of a tree', example: 'The table is made of wood.' }],
  ['hill', { definition: 'a raised area of land, smaller than a mountain', example: 'We walked up the hill.' }],
  ['smith', { definition: 'a worker who shapes metal, especially a blacksmith', example: 'The smith made horseshoes.' }],
  ['hall', { definition: 'a large room or building used for meetings and public events', example: 'The concert was in the town hall.' }],
  ['guest', { definition: 'a person invited to visit or stay in the home of someone else', example: 'We have a guest for dinner.' }],
  ['ball', { definition: 'a round object used in games and sports', example: 'Throw the ball to me.' }],
  ['stone', { definition: 'a hard solid mineral material; a small piece of rock', example: 'The path is made of stone.' }],
  ['nation', { definition: 'a large group of people living in one country under one government', example: 'The whole nation celebrated.' }],
  ['lines', { definition: 'long thin marks on a surface', example: 'Draw two lines on the paper.' }],
  ['brown', { definition: 'a color like that of earth or chocolate', example: 'Her eyes are brown.' }],
  ['grant', { definition: 'an amount of money given for a special purpose', example: 'The school received a research grant.' }],
  ['worth', { definition: 'the value of something in money or importance', example: 'The painting has great worth.' }],
  ['sellers', { definition: 'people who sell things', example: 'The market is full of sellers.' }],
  ['begin', { definition: 'to start doing something', example: 'The class will begin at nine.' }],
  ['as', { definition: 'used to say what someone or something is like, or to compare two things', example: 'He works as a teacher.' }],
  ['planet', { definition: '(astronomy) a large celestial body that revolves around a star; the solar system has eight planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune', example: 'Earth is the third planet from the sun.' }],
  /*
   * Second audit pass (top ~2500 by frequency). Same failure classes:
   * famous-person first synsets ("truth" -> Sojourner Truth, "snow" -> the
   * novelist C. P. Snow), wrong-domain senses ("book" -> the Koran,
   * "monitor" -> the Civil War ironclad, "makes" -> the MAK terrorist
   * group), US-government department senses for everyday abstract nouns,
   * and non-primary senses a learner would never want first. Words the
   * technical curriculum claims (base, energy, mass, second, time, power)
   * are deliberately NOT overridden — technical layering wins anyway.
   */
  ['amazon', { definition: 'a very long river in South America that flows through the largest rain forest in the world', example: 'The Amazon carries more water than any other river.' }],
  ['army', { definition: 'a large organized group of soldiers trained to fight on land', example: 'He joined the army at eighteen.' }],
  ['bank', { definition: 'a business where people keep, save, and borrow money', example: 'She took money out of the bank.' }],
  ['bar', { definition: 'a long straight piece of metal or wood; also a place that serves drinks', example: 'The window had iron bars.' }],
  ['bill', { definition: 'a piece of paper that shows how much money you must pay', example: 'The waiter brought the bill.' }],
  ['billion', { definition: 'the number one thousand million; a one followed by nine zeros', example: 'The country has over a billion people.' }],
  ['book', { definition: 'a set of printed pages bound together for reading', example: 'She read a book about animals.' }],
  ['books', { definition: 'sets of printed pages bound together for reading', example: 'The library is full of books.' }],
  ['brother', { definition: 'a boy or man who has the same parents as another person', example: 'My brother is two years older than me.' }],
  ['bush', { definition: 'a plant with many woody branches, smaller than a tree', example: 'A bird hid in the bush.' }],
  ['capital', { definition: 'the city where the government of a country works; also money used to start a business', example: 'Paris is the capital of France.' }],
  ['chain', { definition: 'a line of metal rings joined together', example: 'The dog was tied with a chain.' }],
  ['charles', { definition: 'a common first name for a man', example: 'Charles is my neighbor.' }],
  ['commerce', { definition: 'the buying and selling of goods and services', example: 'The port is a center of commerce.' }],
  ['congress', { definition: 'a group of people elected to make the laws of a country; a formal meeting of representatives', example: 'Congress voted on the new law.' }],
  ['court', { definition: 'a place where legal cases are heard and judged; also an area marked out for games like tennis', example: 'The case went to court.' }],
  ['david', { definition: 'a common first name for a man', example: 'David works at the school.' }],
  ['defense', { definition: 'the act of protecting someone or something from attack', example: 'The wall was built for defense.' }],
  ['doctor', { definition: 'a person trained to treat sick and injured people', example: 'The doctor examined the patient.' }],
  ['dog', { definition: 'a four-legged animal often kept as a pet, known for its loyalty', example: 'The dog barked at the mailman.' }],
  ['draft', { definition: 'an early version of a piece of writing that will be improved later', example: 'She wrote the first draft of her essay.' }],
  ['drive', { definition: 'to operate and steer a vehicle such as a car', example: 'She learned to drive last year.' }],
  ['eastern', { definition: 'in, from, or toward the east', example: 'They live on the eastern side of the city.' }],
  ['education', { definition: 'the process of teaching and learning knowledge and skills', example: 'A good education opens many doors.' }],
  ['eight', { definition: 'the number that is one more than seven; 8', example: 'The spider has eight legs.' }],
  ['extra', { definition: 'more than what is usual or needed', example: 'Bring an extra pair of socks.' }],
  ['fall', { definition: 'to drop down toward the ground; also the season between summer and winter', example: 'Leaves fall from the trees in autumn.' }],
  ['father', { definition: 'a male parent', example: 'His father taught him to fish.' }],
  ['felt', { definition: 'the past form of the verb feel; also a soft thick cloth made of pressed fibers', example: 'She felt happy about the news.' }],
  ['fields', { definition: 'open areas of land, often used for growing crops', example: 'The farmer planted corn in the fields.' }],
  ['fix', { definition: 'to repair something that is broken', example: 'Can you fix my bicycle?' }],
  ['flat', { definition: 'smooth and level, with no bumps or slopes', example: 'The table has a flat surface.' }],
  ['ford', { definition: 'a shallow place in a river where people can walk or drive across', example: 'The horses crossed the river at the ford.' }],
  ['frame', { definition: 'a border of wood or metal that holds or surrounds something, such as a picture', example: 'The photo is in a silver frame.' }],
  ['ga', { definition: 'a short written form of Georgia, a state in the American South', example: 'The address ends with GA for Georgia.' }],
  ['gamma', { definition: 'the third letter of the Greek alphabet', example: 'Gamma comes after alpha and beta.' }],
  ['george', { definition: 'a common first name for a man', example: 'George lives next door.' }],
  ['green', { definition: 'the color of grass and leaves', example: 'The leaves turn green in spring.' }],
  ['id', { definition: 'a card or document that shows who a person is; short for identification', example: 'Please show your ID at the door.' }],
  ['jackson', { definition: 'a common English family name', example: 'Mr. Jackson teaches history.' }],
  ['james', { definition: 'a common first name for a man', example: 'James plays on our team.' }],
  ['java', { definition: 'a widely used programming language; also an informal word for coffee', example: 'The application is written in Java.' }],
  ['john', { definition: 'a common first name for a man', example: 'John is coming to dinner.' }],
  ['johnson', { definition: 'a common English family name', example: 'The Johnsons live across the street.' }],
  ['jones', { definition: 'a common English family name', example: 'Mrs. Jones runs the bakery.' }],
  ['justice', { definition: 'fair treatment of people according to the law and what is right', example: 'The victims asked for justice.' }],
  ['lead', { definition: 'to go in front and show the way; to be in charge of a group', example: 'She will lead the team this year.' }],
  ['lee', { definition: 'the side of something that is sheltered from the wind', example: 'The ship anchored in the lee of the island.' }],
  ['louis', { definition: 'a common first name for a man', example: 'Louis moved here from France.' }],
  ['lyrics', { definition: 'the words of a song', example: 'She knows the lyrics by heart.' }],
  ['makes', { definition: 'to create or produce something; the form of make used with he, she, or it', example: 'She makes bread every morning.' }],
  ['man', { definition: 'an adult male human', example: 'The man opened the door for us.' }],
  ['march', { definition: 'a walk with regular steps, especially by soldiers; also the third month of the year', example: 'The soldiers began their march at dawn.' }],
  ['mark', { definition: 'a small spot, line, or sign on a surface', example: 'The pen left a mark on the table.' }],
  ['martin', { definition: 'a small bird with a forked tail that catches insects while flying', example: 'A martin built a nest under the roof.' }],
  ['mary', { definition: 'a common first name for a woman', example: 'Mary sings in the choir.' }],
  ['mean', { definition: 'to have a particular sense or to signify something', example: 'What does this word mean?' }],
  ['means', { definition: 'a way or method of doing or achieving something', example: 'The train is a fast means of travel.' }],
  ['monitor', { definition: 'a screen that shows pictures and text from a computer', example: 'The monitor went dark when the power failed.' }],
  ['net', { definition: 'material made of knotted string with holes in it, used to catch fish or in sports', example: 'The fisherman pulled in the net.' }],
  ['night', { definition: 'the time of darkness between sunset and sunrise', example: 'The stars come out at night.' }],
  ['northern', { definition: 'in, from, or toward the north', example: 'Winters are cold in the northern regions.' }],
  ['orange', { definition: 'a round juicy fruit with a thick skin; also the color of this fruit', example: 'She peeled an orange for breakfast.' }],
  ['paul', { definition: 'a common first name for a man', example: 'Paul fixed the fence yesterday.' }],
  ['peter', { definition: 'a common first name for a man', example: 'Peter rides his bike to work.' }],
  ['plant', { definition: 'a living thing that grows in the ground, such as a flower or tree', example: 'Water the plant twice a week.' }],
  ['pop', { definition: 'a short sharp sound; also popular music', example: 'The balloon burst with a loud pop.' }],
  ['president', { definition: 'the elected leader of a republic; the head of an organization', example: 'The president gave a speech to the nation.' }],
  ['rape', { definition: 'the crime of forcing another person to have sex', example: 'Rape is a serious crime.' }],
  ['read', { definition: 'to look at written words and understand their meaning', example: 'She likes to read before bed.' }],
  ['reading', { definition: 'the activity of looking at written words and understanding them', example: 'Reading is her favorite hobby.' }],
  ['ring', { definition: 'a circle of metal worn on the finger; also the sound of a bell', example: 'He gave her a gold ring.' }],
  ['robert', { definition: 'a common first name for a man', example: 'Robert drives the school bus.' }],
  ['rose', { definition: 'a garden flower with a sweet smell and thorns on its stem', example: 'He gave her a red rose.' }],
  ['saw', { definition: 'a tool with a sharp toothed blade used for cutting wood', example: 'He cut the board with a saw.' }],
  ['scott', { definition: 'a common first name and family name', example: 'Scott joined the team last week.' }],
  ['senate', { definition: 'the smaller and more senior group of lawmakers in some governments', example: 'The senate passed the new bill.' }],
  ['server', { definition: 'a computer that stores information and sends it to other computers; also a person who serves food', example: 'The website is down because the server crashed.' }],
  ['snow', { definition: 'soft white pieces of frozen water that fall from the sky in cold weather', example: 'The children played in the snow.' }],
  ['sound', { definition: 'anything that can be heard', example: 'The sound of rain helped her sleep.' }],
  ['southern', { definition: 'in, from, or toward the south', example: 'Oranges grow in the southern part of the country.' }],
  ['state', { definition: 'the condition that a person or thing is in; also a region of a country with its own government', example: 'The old house was in a poor state.' }],
  ['states', { definition: 'regions of a country that each have their own government', example: 'The country is divided into fifty states.' }],
  ['sub', { definition: 'a short word for a submarine; also a long sandwich', example: 'The sub dived below the waves.' }],
  ['thomas', { definition: 'a common first name for a man', example: 'Thomas repaired the roof.' }],
  ['transportation', { definition: 'the moving of people or goods from one place to another', example: 'The city needs better public transportation.' }],
  ['truth', { definition: 'the real facts about something; what is actually true', example: 'She always tells the truth.' }],
  ['uses', { definition: 'to employ something for a purpose; the form of use used with he, she, or it', example: 'She uses a pen to write.' }],
  ['vegas', { definition: 'an informal name for Las Vegas, a city famous for its casinos', example: 'They flew to Vegas for the weekend.' }],
  ['web', { definition: 'a net of thin threads spun by a spider; also the system of linked pages on the internet', example: 'The spider spun a web in the corner.' }],
  ['williams', { definition: 'a common English family name', example: 'Dr. Williams works at the clinic.' }],
  ['windows', { definition: 'openings in a wall filled with glass that let in light and air', example: 'Open the windows to let in fresh air.' }],
  ['york', { definition: 'a historic city in the north of England', example: 'York is famous for its old walls.' }]
]);

/** Apply the curated sense overrides to a deck slice, preserving order. */
export function applyDefinitionOverrides(deck: readonly DeckWord[]): DeckWord[] {
  return deck.map((entry) => {
    const override = DEFINITION_OVERRIDES.get(entry.word);
    return override === undefined ? entry : { ...entry, definition: override.definition, example: override.example };
  });
}
