import type { DeckWord } from '../deck';

/**
 * Starter-100 deck: the most common concrete English words, with plain
 * definitions and simple example sentences. Hand-curated content.
 *
 * Derived from standard high-frequency word lists (public domain), with
 * definitions written in learner English.
 */
export const DECK_100: readonly DeckWord[] = [
  { word: 'apple', definition: 'a round red or green fruit', example: 'I eat an apple every morning.' },
  { word: 'water', definition: 'the clear liquid we drink', example: 'Please give me a glass of water.' },
  { word: 'friend', definition: 'a person you like and trust', example: 'My friend and I play together.' },
  { word: 'house', definition: 'a building where people live', example: 'They live in a small house.' },
  { word: 'morning', definition: 'the early part of the day', example: 'I wake up early in the morning.' },
  { word: 'book', definition: 'pages with words that you read', example: 'She is reading an interesting book.' },
  { word: 'travel', definition: 'to go from one place to another', example: 'We travel by train in summer.' },
  { word: 'music', definition: 'sounds arranged to be pleasant', example: 'He listens to music at night.' },
  { word: 'learn', definition: 'to get new knowledge or skill', example: 'I want to learn to speak English.' },
  { word: 'speak', definition: 'to say words out loud', example: 'Can you speak more slowly, please?' },
  { word: 'work', definition: 'an activity done as a job', example: 'She goes to work by bus.' },
  { word: 'sleep', definition: 'to rest with your eyes closed', example: 'I sleep eight hours every night.' },
  { word: 'eat', definition: 'to put food in your mouth and swallow it', example: 'We eat dinner at seven.' },
  { word: 'drink', definition: 'to take liquid into your mouth', example: 'He drinks coffee in the morning.' },
  { word: 'run', definition: 'to move fast on your feet', example: 'I run in the park every day.' },
  { word: 'walk', definition: 'to move on foot at a normal speed', example: 'We walk to school together.' },
  { word: 'see', definition: 'to notice something with your eyes', example: 'I can see the mountains from here.' },
  { word: 'hear', definition: 'to notice sound with your ears', example: 'Did you hear that strange noise?' },
  { word: 'say', definition: 'to speak words', example: 'Please say my name slowly.' },
  { word: 'ask', definition: 'to say a question', example: 'May I ask you something?' },
  { word: 'answer', definition: 'to reply to a question', example: 'She answered the question quickly.' },
  { word: 'open', definition: 'to move something so it is not closed', example: 'Open the window, please.' },
  { word: 'close', definition: 'to shut something', example: 'Close the door when you leave.' },
  { word: 'give', definition: 'to hand something to someone', example: 'Give me the book, please.' },
  { word: 'take', definition: 'to get something with your hand', example: 'Take an umbrella with you.' },
  { word: 'come', definition: 'to move toward this place', example: 'Come to my house after school.' },
  { word: 'go', definition: 'to move away from this place', example: 'I go to the market on Sunday.' },
  { word: 'make', definition: 'to create or build something', example: 'She makes breakfast every day.' },
  { word: 'know', definition: 'to have information in your mind', example: 'I know the answer to that.' },
  { word: 'think', definition: 'to use your mind', example: 'Think about it for a moment.' },
  { word: 'want', definition: 'to wish for something', example: 'I want a cup of tea.' },
  { word: 'need', definition: 'to require something important', example: 'Plants need water and light.' },
  { word: 'like', definition: 'to enjoy something', example: 'I like warm summer days.' },
  { word: 'love', definition: 'to care about someone very much', example: 'Parents love their children.' },
  { word: 'help', definition: 'to do something useful for someone', example: 'Can you help me carry this?' },
  { word: 'find', definition: 'to discover something you were looking for', example: 'I cannot find my keys.' },
  { word: 'keep', definition: 'to continue to have something', example: 'Keep the change, please.' },
  { word: 'begin', definition: 'to start something', example: 'The movie begins at eight.' },
  { word: 'stop', definition: 'to end an action', example: 'The bus stops at the corner.' },
  { word: 'try', definition: 'to make an effort', example: 'Try again; you can do it.' },
  { word: 'wait', definition: 'to stay until something happens', example: 'Please wait a minute.' },
  { word: 'watch', definition: 'to look at something for a time', example: 'We watch the news at night.' },
  { word: 'listen', definition: 'to pay attention to sound', example: 'Listen carefully to the teacher.' },
  { word: 'read', definition: 'to look at words and understand them', example: 'I read a book before bed.' },
  { word: 'write', definition: 'to make words on paper or a screen', example: 'Write your name here.' },
  { word: 'buy', definition: 'to get something with money', example: 'I buy bread from the bakery.' },
  { word: 'sell', definition: 'to give something for money', example: 'They sell fresh fruit here.' },
  { word: 'pay', definition: 'to give money for something', example: 'I pay the rent on the first.' },
  { word: 'play', definition: 'to do something for fun', example: 'The children play in the yard.' },
  { word: 'sing', definition: 'to make music with your voice', example: 'She sings in the choir.' },
  { word: 'cook', definition: 'to prepare food with heat', example: 'He cooks pasta for lunch.' },
  { word: 'wash', definition: 'to clean with water', example: 'Wash your hands before eating.' },
  { word: 'wear', definition: 'to have clothes on your body', example: 'I wear a coat in winter.' },
  { word: 'meet', definition: 'to see someone for the first time', example: 'Nice to meet you.' },
  { word: 'call', definition: 'to phone someone', example: 'Call me when you arrive.' },
  { word: 'send', definition: 'to make something go to someone', example: 'Send me an email tonight.' },
  { word: 'bring', definition: 'to carry something to a place', example: 'Bring a friend to the party.' },
  { word: 'carry', definition: 'to hold something while moving', example: 'She carries a heavy bag.' },
  { word: 'put', definition: 'to place something somewhere', example: 'Put the cup on the table.' },
  { word: 'sit', definition: 'to rest on a chair', example: 'Please sit down here.' },
  { word: 'stand', definition: 'to be on your feet', example: 'We stand in line for tickets.' },
  { word: 'fall', definition: 'to drop down to the ground', example: 'Leaves fall in autumn.' },
  { word: 'grow', definition: 'to become bigger', example: 'Trees grow slowly.' },
  { word: 'break', definition: 'to damage something into pieces', example: 'Do not break the glass.' },
  { word: 'fix', definition: 'to repair something broken', example: 'He can fix the old radio.' },
  { word: 'build', definition: 'to make a structure', example: 'They build a new bridge.' },
  { word: 'cut', definition: 'to divide with something sharp', example: 'Cut the paper in half.' },
  { word: 'draw', definition: 'to make a picture with a pen', example: 'She draws animals very well.' },
  { word: 'paint', definition: 'to cover a surface with color', example: 'We paint the wall blue.' },
  { word: 'count', definition: 'to say numbers in order', example: 'Count from one to ten.' },
  { word: 'spend', definition: 'to use money or time', example: 'We spend Sundays at home.' },
  { word: 'save', definition: 'to keep something for later', example: 'Save some cake for your sister.' },
  { word: 'share', definition: 'to give part of something to others', example: 'Share the toys with your brother.' },
  { word: 'choose', definition: 'to pick one thing from many', example: 'Choose a color you like.' },
  { word: 'believe', definition: 'to think something is true', example: 'I believe you are right.' },
  { word: 'remember', definition: 'to keep something in your mind', example: 'Remember to lock the door.' },
  { word: 'forget', definition: 'to not remember', example: 'Do not forget your keys.' },
  { word: 'understand', definition: 'to know the meaning of something', example: 'Now I understand the lesson.' },
  { word: 'explain', definition: 'to make something clear to someone', example: 'Can you explain this rule?' },
  { word: 'agree', definition: 'to have the same opinion', example: 'I agree with your idea.' },
  { word: 'promise', definition: 'to say you will do something', example: 'I promise to come early.' },
  { word: 'happy', definition: 'feeling good and pleased', example: 'The children are happy today.' },
  { word: 'sad', definition: 'feeling unhappy', example: 'She felt sad at the end of the movie.' },
  { word: 'angry', definition: 'feeling strong displeasure', example: 'He was angry about the mistake.' },
  { word: 'tired', definition: 'needing rest or sleep', example: 'I am tired after the long walk.' },
  { word: 'hungry', definition: 'wanting to eat', example: 'We are hungry; let us eat.' },
  { word: 'thirsty', definition: 'wanting to drink', example: 'The runners are thirsty.' },
  { word: 'cold', definition: 'having a low temperature', example: 'It is cold in winter.' },
  { word: 'hot', definition: 'having a high temperature', example: 'The soup is very hot.' },
  { word: 'big', definition: 'large in size', example: 'An elephant is a big animal.' },
  { word: 'small', definition: 'little in size', example: 'A mouse is a small animal.' },
  { word: 'fast', definition: 'moving quickly', example: 'The train is very fast.' },
  { word: 'slow', definition: 'moving without speed', example: 'The turtle is slow.' },
  { word: 'easy', definition: 'not difficult', example: 'This exercise is easy.' },
  { word: 'hard', definition: 'difficult to do', example: 'That test was very hard.' },
  { word: 'new', definition: 'recently made or bought', example: 'She has a new bicycle.' },
  { word: 'old', definition: 'having lived or existed for a long time', example: 'That is a very old house.' },
  { word: 'good', definition: 'pleasant and of high quality', example: 'This is a good movie.' },
  { word: 'bad', definition: 'not good', example: 'The weather is bad today.' },
  { word: 'beautiful', definition: 'very pleasing to look at', example: 'The garden is beautiful in spring.' }
];
