import type { Relation, RelationPredicate } from '../relations';

/**
 * SUPPLEMENTAL EVERYDAY RELATIONS — hand-authored edges for the domains the
 * technical curriculum skips.
 *
 * The precision-first extractor mines edges from WordNet glosses, but only
 * about 34% of defined words carry a mined edge — everyday knowledge like
 * "dog is-a animal" or "knife is used for cutting" often hides in phrasing
 * the regex honestly refuses to parse. These edges close that relational
 * coverage gap the same way the technical curriculum does: they flow through
 * the authored-edge path (origin 'authored') and are filtered to knownWords
 * at merge time, so an edge whose subject or object the observer has not met
 * simply stays dormant. Every edge is a plain, true, uncontroversial school
 * fact; a wrong edge poisons inheritance, so nothing contested is authored.
 *
 * Subjects and objects are common lowercase English words chosen to be in
 * the 20k frequency deck (verified against it), with two deliberate
 * exceptions — 'mammal' and 'reptile' — which are not deck words today but
 * anchor the classic category chains; their edges activate the moment a deck
 * or chaperone introduces them, and are harmlessly filtered until then.
 */

const SOURCE = 'everyday-knowledge curriculum';

const edge = (subject: string, predicate: RelationPredicate, object: string): Relation => ({
  subject,
  predicate,
  object,
  source: SOURCE,
  origin: 'authored'
});

export const SUPPLEMENTAL_RELATIONS: readonly Relation[] = [
  // ── ANIMALS: category chains, parts, and abilities ─────────────────────
  edge('dog', 'is-a', 'animal'),
  edge('dog', 'is-a', 'mammal'),
  edge('dog', 'is-a', 'pet'),
  edge('dog', 'has-part', 'legs'),
  edge('dog', 'has-part', 'tail'),
  edge('dog', 'has-part', 'fur'),
  edge('dog', 'capable-of', 'run'),
  edge('dog', 'capable-of', 'swim'),
  edge('dog', 'capable-of', 'bark'),
  edge('cat', 'is-a', 'animal'),
  edge('cat', 'is-a', 'mammal'),
  edge('cat', 'is-a', 'pet'),
  edge('cat', 'has-part', 'fur'),
  edge('cat', 'has-part', 'tail'),
  edge('cat', 'has-part', 'claw'),
  edge('cat', 'capable-of', 'climb'),
  edge('cat', 'capable-of', 'jump'),
  edge('horse', 'is-a', 'animal'),
  edge('horse', 'is-a', 'mammal'),
  edge('horse', 'has-part', 'tail'),
  edge('horse', 'has-part', 'legs'),
  edge('horse', 'capable-of', 'run'),
  edge('horse', 'capable-of', 'jump'),
  edge('horse', 'used-for', 'riding'),
  edge('cow', 'is-a', 'animal'),
  edge('cow', 'is-a', 'mammal'),
  edge('cow', 'has-part', 'tail'),
  edge('cow', 'has-part', 'legs'),
  edge('pig', 'is-a', 'animal'),
  edge('pig', 'is-a', 'mammal'),
  edge('pig', 'has-part', 'tail'),
  edge('sheep', 'is-a', 'animal'),
  edge('sheep', 'is-a', 'mammal'),
  edge('sheep', 'has-part', 'wool'),
  edge('goat', 'is-a', 'animal'),
  edge('goat', 'is-a', 'mammal'),
  edge('deer', 'is-a', 'animal'),
  edge('deer', 'is-a', 'mammal'),
  edge('deer', 'capable-of', 'run'),
  edge('deer', 'capable-of', 'jump'),
  edge('bird', 'is-a', 'animal'),
  edge('bird', 'has-part', 'wings'),
  edge('bird', 'has-part', 'feathers'),
  edge('bird', 'has-part', 'legs'),
  edge('bird', 'capable-of', 'fly'),
  edge('bird', 'capable-of', 'sing'),
  edge('robin', 'is-a', 'bird'),
  edge('robin', 'has-part', 'wings'),
  edge('robin', 'capable-of', 'fly'),
  edge('robin', 'capable-of', 'sing'),
  edge('eagle', 'is-a', 'bird'),
  edge('eagle', 'has-part', 'wings'),
  edge('eagle', 'has-part', 'claw'),
  edge('eagle', 'capable-of', 'fly'),
  edge('owl', 'is-a', 'bird'),
  edge('owl', 'has-part', 'feathers'),
  edge('owl', 'capable-of', 'fly'),
  edge('duck', 'is-a', 'bird'),
  edge('duck', 'has-part', 'feathers'),
  edge('duck', 'capable-of', 'swim'),
  edge('duck', 'capable-of', 'fly'),
  edge('chicken', 'is-a', 'bird'),
  edge('chicken', 'has-part', 'feathers'),
  edge('chicken', 'has-part', 'wings'),
  edge('penguin', 'is-a', 'bird'),
  edge('penguin', 'has-part', 'feathers'),
  edge('penguin', 'capable-of', 'swim'),
  edge('fish', 'is-a', 'animal'),
  edge('fish', 'has-part', 'fins'),
  edge('fish', 'has-part', 'scales'),
  edge('fish', 'has-part', 'tail'),
  edge('fish', 'capable-of', 'swim'),
  edge('fish', 'located-in', 'water'),
  edge('shark', 'is-a', 'fish'),
  edge('shark', 'has-part', 'fins'),
  edge('shark', 'has-part', 'teeth'),
  edge('shark', 'capable-of', 'swim'),
  edge('shark', 'located-in', 'ocean'),
  edge('whale', 'is-a', 'animal'),
  edge('whale', 'is-a', 'mammal'),
  edge('whale', 'has-part', 'tail'),
  edge('whale', 'capable-of', 'swim'),
  edge('whale', 'located-in', 'ocean'),
  edge('dolphin', 'is-a', 'animal'),
  edge('dolphin', 'is-a', 'mammal'),
  edge('dolphin', 'capable-of', 'swim'),
  edge('dolphin', 'located-in', 'ocean'),
  edge('snake', 'is-a', 'animal'),
  edge('snake', 'is-a', 'reptile'),
  edge('snake', 'has-part', 'scales'),
  edge('snake', 'capable-of', 'crawl'),
  edge('lizard', 'is-a', 'animal'),
  edge('lizard', 'is-a', 'reptile'),
  edge('lizard', 'has-part', 'tail'),
  edge('lizard', 'has-part', 'legs'),
  edge('lizard', 'has-part', 'scales'),
  edge('turtle', 'is-a', 'animal'),
  edge('turtle', 'is-a', 'reptile'),
  edge('turtle', 'has-part', 'shell'),
  edge('turtle', 'capable-of', 'swim'),
  edge('frog', 'is-a', 'animal'),
  edge('frog', 'capable-of', 'jump'),
  edge('frog', 'capable-of', 'swim'),
  edge('frog', 'located-in', 'pond'),
  edge('bee', 'is-a', 'insect'),
  edge('bee', 'has-part', 'wings'),
  edge('bee', 'has-part', 'legs'),
  edge('bee', 'capable-of', 'fly'),
  edge('ant', 'is-a', 'insect'),
  edge('ant', 'has-part', 'legs'),
  edge('fly', 'is-a', 'insect'),
  edge('fly', 'has-part', 'wings'),
  edge('butterfly', 'is-a', 'insect'),
  edge('butterfly', 'has-part', 'wings'),
  edge('butterfly', 'capable-of', 'fly'),
  edge('spider', 'is-a', 'animal'),
  edge('spider', 'has-part', 'legs'),
  edge('spider', 'capable-of', 'climb'),
  edge('insect', 'is-a', 'animal'),
  edge('insect', 'has-part', 'legs'),
  edge('mammal', 'is-a', 'animal'),
  edge('mammal', 'has-part', 'hair'),
  edge('reptile', 'is-a', 'animal'),
  edge('reptile', 'has-part', 'scales'),
  edge('lion', 'is-a', 'animal'),
  edge('lion', 'is-a', 'mammal'),
  edge('lion', 'has-part', 'teeth'),
  edge('lion', 'capable-of', 'run'),
  edge('lion', 'capable-of', 'hunt'),
  edge('tiger', 'is-a', 'animal'),
  edge('tiger', 'is-a', 'mammal'),
  edge('tiger', 'has-part', 'stripes'),
  edge('tiger', 'capable-of', 'hunt'),
  edge('bear', 'is-a', 'animal'),
  edge('bear', 'is-a', 'mammal'),
  edge('bear', 'has-part', 'fur'),
  edge('bear', 'capable-of', 'swim'),
  edge('bear', 'capable-of', 'climb'),
  edge('wolf', 'is-a', 'animal'),
  edge('wolf', 'is-a', 'mammal'),
  edge('wolf', 'has-part', 'fur'),
  edge('wolf', 'capable-of', 'run'),
  edge('wolf', 'capable-of', 'hunt'),
  edge('fox', 'is-a', 'animal'),
  edge('fox', 'is-a', 'mammal'),
  edge('fox', 'has-part', 'fur'),
  edge('fox', 'has-part', 'tail'),
  edge('rabbit', 'is-a', 'animal'),
  edge('rabbit', 'is-a', 'mammal'),
  edge('rabbit', 'has-part', 'fur'),
  edge('rabbit', 'has-part', 'ears'),
  edge('rabbit', 'capable-of', 'jump'),
  edge('mouse', 'is-a', 'animal'),
  edge('mouse', 'is-a', 'mammal'),
  edge('mouse', 'has-part', 'tail'),
  edge('mouse', 'has-part', 'fur'),
  edge('elephant', 'is-a', 'animal'),
  edge('elephant', 'is-a', 'mammal'),
  edge('elephant', 'has-part', 'trunk'),
  edge('elephant', 'has-part', 'ears'),
  edge('monkey', 'is-a', 'animal'),
  edge('monkey', 'is-a', 'mammal'),
  edge('monkey', 'has-part', 'tail'),
  edge('monkey', 'capable-of', 'climb'),
  edge('bat', 'is-a', 'animal'),
  edge('bat', 'is-a', 'mammal'),
  edge('bat', 'has-part', 'wings'),
  edge('bat', 'capable-of', 'fly'),

  // ── FOOD: kinds, composition, and simple properties ────────────────────
  edge('apple', 'is-a', 'fruit'),
  edge('apple', 'has-part', 'seeds'),
  edge('banana', 'is-a', 'fruit'),
  edge('orange', 'is-a', 'fruit'),
  edge('grape', 'is-a', 'fruit'),
  edge('lemon', 'is-a', 'fruit'),
  edge('lemon', 'has-property', 'sour'),
  edge('pear', 'is-a', 'fruit'),
  edge('peach', 'is-a', 'fruit'),
  edge('cherry', 'is-a', 'fruit'),
  edge('berry', 'is-a', 'fruit'),
  edge('strawberry', 'is-a', 'fruit'),
  edge('fruit', 'is-a', 'food'),
  edge('fruit', 'has-part', 'seeds'),
  edge('vegetable', 'is-a', 'food'),
  edge('carrot', 'is-a', 'vegetable'),
  edge('potato', 'is-a', 'vegetable'),
  edge('onion', 'is-a', 'vegetable'),
  edge('pea', 'is-a', 'vegetable'),
  edge('bean', 'is-a', 'vegetable'),
  edge('corn', 'is-a', 'food'),
  edge('bread', 'is-a', 'food'),
  edge('bread', 'made-of', 'flour'),
  edge('cake', 'is-a', 'food'),
  edge('cake', 'made-of', 'flour'),
  edge('cheese', 'is-a', 'food'),
  edge('cheese', 'made-of', 'milk'),
  edge('butter', 'is-a', 'food'),
  edge('butter', 'made-of', 'milk'),
  edge('milk', 'is-a', 'drink'),
  edge('milk', 'is-a', 'liquid'),
  edge('egg', 'is-a', 'food'),
  edge('rice', 'is-a', 'food'),
  edge('meat', 'is-a', 'food'),
  edge('soup', 'is-a', 'food'),
  edge('honey', 'is-a', 'food'),
  edge('honey', 'has-property', 'sweet'),
  edge('sugar', 'has-property', 'sweet'),
  edge('juice', 'is-a', 'drink'),
  edge('juice', 'made-of', 'fruit'),
  edge('tea', 'is-a', 'drink'),
  edge('coffee', 'is-a', 'drink'),
  edge('water', 'is-a', 'liquid'),
  edge('water', 'used-for', 'drinking'),

  // ── TOOLS, HOUSEHOLD, BUILDINGS, VEHICLES ──────────────────────────────
  edge('hammer', 'is-a', 'tool'),
  edge('hammer', 'used-for', 'building'),
  edge('knife', 'is-a', 'tool'),
  edge('knife', 'has-part', 'blade'),
  edge('knife', 'has-part', 'handle'),
  edge('knife', 'used-for', 'cutting'),
  edge('spoon', 'is-a', 'tool'),
  edge('spoon', 'used-for', 'eating'),
  edge('fork', 'is-a', 'tool'),
  edge('fork', 'used-for', 'eating'),
  edge('saw', 'is-a', 'tool'),
  edge('saw', 'used-for', 'cutting'),
  edge('scissors', 'used-for', 'cutting'),
  edge('pen', 'used-for', 'writing'),
  edge('pencil', 'used-for', 'writing'),
  edge('brush', 'used-for', 'painting'),
  edge('chair', 'is-a', 'furniture'),
  edge('chair', 'has-part', 'legs'),
  edge('chair', 'used-for', 'sitting'),
  edge('table', 'is-a', 'furniture'),
  edge('table', 'has-part', 'legs'),
  edge('bed', 'is-a', 'furniture'),
  edge('bed', 'used-for', 'sleeping'),
  edge('desk', 'is-a', 'furniture'),
  edge('lamp', 'used-for', 'light'),
  edge('cup', 'used-for', 'drinking'),
  edge('plate', 'used-for', 'eating'),
  edge('bowl', 'used-for', 'eating'),
  edge('oven', 'used-for', 'cooking'),
  edge('pot', 'used-for', 'cooking'),
  edge('pan', 'used-for', 'cooking'),
  edge('house', 'is-a', 'building'),
  edge('house', 'has-part', 'roof'),
  edge('house', 'has-part', 'door'),
  edge('house', 'has-part', 'window'),
  edge('house', 'has-part', 'wall'),
  edge('school', 'is-a', 'building'),
  edge('church', 'is-a', 'building'),
  edge('window', 'made-of', 'glass'),
  edge('book', 'made-of', 'paper'),
  edge('book', 'has-part', 'pages'),
  edge('paper', 'made-of', 'wood'),
  edge('coin', 'made-of', 'metal'),
  edge('car', 'is-a', 'vehicle'),
  edge('car', 'has-part', 'wheels'),
  edge('car', 'has-part', 'engine'),
  edge('car', 'used-for', 'travel'),
  edge('bus', 'is-a', 'vehicle'),
  edge('truck', 'is-a', 'vehicle'),
  edge('train', 'is-a', 'vehicle'),
  edge('train', 'has-part', 'engine'),
  edge('boat', 'is-a', 'vehicle'),
  edge('boat', 'located-in', 'water'),
  edge('plane', 'is-a', 'vehicle'),
  edge('plane', 'has-part', 'wings'),
  edge('plane', 'capable-of', 'fly'),
  edge('plane', 'used-for', 'travel'),
  edge('bicycle', 'is-a', 'vehicle'),
  edge('bicycle', 'has-part', 'wheels'),
  edge('ship', 'is-a', 'vehicle'),
  edge('ship', 'located-in', 'ocean'),

  // ── BODY: part structure and function ──────────────────────────────────
  edge('body', 'has-part', 'head'),
  edge('body', 'has-part', 'arms'),
  edge('body', 'has-part', 'legs'),
  edge('body', 'has-part', 'hands'),
  edge('body', 'has-part', 'feet'),
  edge('body', 'has-part', 'skin'),
  edge('body', 'has-part', 'heart'),
  edge('body', 'has-part', 'brain'),
  edge('head', 'has-part', 'eyes'),
  edge('head', 'has-part', 'ears'),
  edge('head', 'has-part', 'nose'),
  edge('head', 'has-part', 'mouth'),
  edge('head', 'has-part', 'hair'),
  edge('hand', 'has-part', 'fingers'),
  edge('hand', 'has-part', 'thumb'),
  edge('foot', 'has-part', 'toes'),
  edge('arm', 'has-part', 'elbow'),
  edge('leg', 'has-part', 'knee'),
  edge('finger', 'has-part', 'nail'),
  edge('mouth', 'has-part', 'teeth'),
  edge('mouth', 'has-part', 'tongue'),
  edge('eye', 'used-for', 'seeing'),
  edge('ear', 'used-for', 'hearing'),
  edge('nose', 'used-for', 'breathing'),
  edge('mouth', 'used-for', 'eating'),
  edge('heart', 'is-a', 'organ'),
  edge('heart', 'capable-of', 'beat'),
  edge('lung', 'is-a', 'organ'),
  edge('lung', 'used-for', 'breathing'),
  edge('brain', 'is-a', 'organ'),
  edge('brain', 'used-for', 'thinking'),
  edge('teeth', 'used-for', 'eating'),

  // ── NATURE AND GEOGRAPHY ───────────────────────────────────────────────
  edge('tree', 'is-a', 'plant'),
  edge('tree', 'has-part', 'leaves'),
  edge('tree', 'has-part', 'branches'),
  edge('tree', 'has-part', 'roots'),
  edge('tree', 'has-part', 'trunk'),
  edge('tree', 'made-of', 'wood'),
  edge('flower', 'is-a', 'plant'),
  edge('flower', 'has-part', 'stem'),
  edge('grass', 'is-a', 'plant'),
  edge('grass', 'has-property', 'green'),
  edge('plant', 'capable-of', 'grow'),
  edge('plant', 'requires', 'water'),
  edge('plant', 'requires', 'light'),
  edge('river', 'capable-of', 'flow'),
  edge('river', 'has-part', 'water'),
  edge('ocean', 'has-part', 'waves'),
  edge('ocean', 'has-part', 'fish'),
  edge('ocean', 'has-property', 'deep'),
  edge('lake', 'has-part', 'water'),
  edge('sea', 'has-part', 'waves'),
  edge('mountain', 'has-part', 'peak'),
  edge('mountain', 'has-property', 'high'),
  edge('island', 'located-in', 'water'),
  edge('forest', 'has-part', 'trees'),
  edge('desert', 'has-property', 'dry'),
  edge('desert', 'has-part', 'sand'),
  edge('beach', 'has-part', 'sand'),
  edge('stone', 'has-property', 'hard'),
  edge('fire', 'has-property', 'hot'),
  edge('fire', 'causes', 'smoke'),
  edge('fire', 'causes', 'heat'),
  edge('ice', 'made-of', 'water'),
  edge('ice', 'has-property', 'cold'),

  // ── CLOTHING ───────────────────────────────────────────────────────────
  edge('shirt', 'is-a', 'clothing'),
  edge('shirt', 'made-of', 'cloth'),
  edge('shirt', 'has-part', 'sleeves'),
  edge('coat', 'is-a', 'clothing'),
  edge('coat', 'used-for', 'warmth'),
  edge('dress', 'is-a', 'clothing'),
  edge('hat', 'is-a', 'clothing'),
  edge('sock', 'is-a', 'clothing'),
  edge('skirt', 'is-a', 'clothing'),
  edge('sweater', 'is-a', 'clothing'),
  edge('scarf', 'is-a', 'clothing'),
  edge('pants', 'is-a', 'clothing'),
  edge('shoe', 'used-for', 'walking'),
  edge('shoe', 'has-part', 'sole'),
  edge('glove', 'has-part', 'fingers'),

  // ── WEATHER ────────────────────────────────────────────────────────────
  edge('rain', 'made-of', 'water'),
  edge('rain', 'has-property', 'wet'),
  edge('rain', 'causes', 'flood'),
  edge('snow', 'has-property', 'cold'),
  edge('snow', 'has-property', 'white'),
  edge('snow', 'made-of', 'ice'),
  edge('wind', 'capable-of', 'blow'),
  edge('storm', 'has-part', 'wind'),
  edge('storm', 'has-part', 'rain'),
  edge('storm', 'causes', 'damage'),
  edge('lightning', 'causes', 'thunder'),
  edge('cloud', 'made-of', 'water'),
  edge('cloud', 'located-in', 'sky'),
  edge('fog', 'made-of', 'water')
];
