/**
 * LOGIC — the truth-functional rule deck.
 *
 * Reduces the curriculum's logic drills to their answers: conjunction and
 * disjunction over decidable arithmetic facts, negation, modus ponens and
 * modus tollens over if-then scenarios, and the two syllogism forms. The
 * drills are generated by `technical/verify.ts`; the parsers here translate
 * each drill's prompt back into a term the engine can reduce, so a rule
 * derivation can be checked against the oracle answer exactly.
 */

import { natFromDecimal } from './peano'
import { FALSE, TRUE, tLit, tSym, termBits, tVar, type Term } from './terms'
import type { RewriteRule } from './types'

const rule = (id: string, lhs: Term, rhs: Term): RewriteRule => ({
  id,
  name: lhs.t === 'sym' ? lhs.head : id,
  lhs,
  rhs,
  origin: 'authored',
  strength: 1,
  sourceClasses: ['curriculum'],
  bits: termBits(lhs) + termBits(rhs),
  active: true,
  createdAt: 0,
  useCount: 0
})

export const LOGIC_RULES: RewriteRule[] = [
  rule('bool.and-true', tSym('bool.and', [TRUE, tVar('x')]), tVar('x')),
  rule('bool.and-false', tSym('bool.and', [FALSE, tVar('x')]), FALSE),
  rule('bool.or-true', tSym('bool.or', [TRUE, tVar('x')]), TRUE),
  rule('bool.or-false', tSym('bool.or', [FALSE, tVar('x')]), tVar('x')),
  rule('bool.not-true', tSym('bool.not', [TRUE]), FALSE),
  rule('bool.not-false', tSym('bool.not', [FALSE]), TRUE),
  rule('logic.mp', tSym('logic.mp', [tSym('imp', [tVar('P'), tVar('Q')]), tVar('P')]), tLit('yes')),
  rule('logic.mt', tSym('logic.mt', [tSym('imp', [tVar('P'), tVar('Q')]), tSym('nq', [tVar('Q')])]), tLit('no')),
  rule(
    'logic.barbara',
    tSym('logic.barbara', [tSym('all', [tVar('M'), tVar('C')]), tSym('isa', [tVar('N'), tVar('M')])]),
    tLit('yes')
  ),
  rule(
    'logic.affirmed',
    tSym('logic.affirmed', [tSym('all', [tVar('M'), tVar('C')]), tSym('isa', [tVar('N'), tVar('C')])]),
    tLit('no')
  )
]

/** Number-words the LOGIC_FACTS table uses: one..twenty. */
const NAT: Readonly<Record<string, number | undefined>> = {
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
  eleven: 11,
  twelve: 12,
  thirteen: 13,
  fourteen: 14,
  fifteen: 15,
  sixteen: 16,
  seventeen: 17,
  eighteen: 18,
  nineteen: 19,
  twenty: 20
}

const nat = (n: number): Term => natFromDecimal(n)

const eq = (a: Term, b: Term): Term => tSym('nat.eq', [a, b])

const parseNat = (match: RegExpMatchArray, index: number): number | null => {
  const word = match[index]
  if (word === undefined) return null
  const value = NAT[word]
  return value === undefined ? null : value
}

/**
 * Parse a LOGIC_FACTS sentence into a reducible nat term: an equality over
 * add/sub/mul/div, or a greater-than / less-than comparison. Null on
 * anything the grammar does not cover.
 */
export function parseLogicFact(text: string): Term | null {
  const source = text.trim().toLowerCase()

  const division = source.match(/^(\w+) divided by (\w+) is (\w+)$/)
  if (division !== null) {
    const a = parseNat(division, 1)
    const b = parseNat(division, 2)
    const result = parseNat(division, 3)
    if (a === null || b === null || result === null) return null
    return eq(tSym('nat.div', [nat(a), nat(b)]), nat(result))
  }

  const arithmetic = source.match(/^(\w+) (plus|minus|times) (\w+) is (\w+)$/)
  if (arithmetic !== null) {
    const a = parseNat(arithmetic, 1)
    const b = parseNat(arithmetic, 3)
    const result = parseNat(arithmetic, 4)
    if (a === null || b === null || result === null) return null
    const op = arithmetic[2] ?? ''
    const lhs =
      op === 'plus' ? tSym('nat.add', [nat(a), nat(b)])
      : op === 'minus' ? tSym('nat.sub', [nat(a), nat(b)])
      : tSym('nat.mul', [nat(a), nat(b)])
    return eq(lhs, nat(result))
  }

  const greater = source.match(/^(\w+) is greater than (\w+)$/)
  if (greater !== null) {
    const a = parseNat(greater, 1)
    const b = parseNat(greater, 2)
    if (a === null || b === null) return null
    return tSym('nat.gt', [nat(a), nat(b)])
  }

  const less = source.match(/^(\w+) is less than (\w+)$/)
  if (less !== null) {
    const a = parseNat(less, 1)
    const b = parseNat(less, 2)
    if (a === null || b === null) return null
    return tSym('nat.lt', [nat(a), nat(b)])
  }

  const plain = source.match(/^(\w+) is (\w+)$/)
  if (plain !== null) {
    const a = parseNat(plain, 1)
    const b = parseNat(plain, 2)
    if (a === null || b === null) return null
    return eq(nat(a), nat(b))
  }

  return null
}

/** An opaque phrase term — identity matters, not content. */
const phrase = (text: string): Term => tSym('phrase', [tLit(text)])

const stripArticle = (text: string): string => text.replace(/^(?:a|an) /, '')

const singularize = (text: string): string =>
  text.length > 1 && text.endsWith('s') && !text.endsWith('ss') ? text.slice(0, -1) : text

/** Lift a noun phrase to its canonical singular form. */
const lifted = (text: string): string => singularize(stripArticle(text.trim()))

/**
 * Parse a logic drill prompt into the term whose reduction states the
 * drill's answer. Null on any unparseable prompt.
 */
export function parseLogicDrill(drill: string, prompt: string): Term | null {
  switch (drill) {
    case 'logic-and':
    case 'logic-or': {
      // The suffix disambiguates: an "A or B" prompt must never parse as
      // logic-and (parseRewritePrompt tries the families in order).
      const pair =
        drill === 'logic-and'
          ? prompt.match(/^statement a says (.+?)\. statement b says (.+?)\. is the statement 'a and b' true or false\??$/i)
          : prompt.match(/^statement a says (.+?)\. statement b says (.+?)\. is the statement 'a or b' true or false\??$/i)
      if (pair === null) return null
      const a = parseLogicFact(pair[1] ?? '')
      const b = parseLogicFact(pair[2] ?? '')
      if (a === null || b === null) return null
      return tSym(drill === 'logic-and' ? 'bool.and' : 'bool.or', [a, b])
    }
    case 'logic-not': {
      const stated = prompt.match(/^(?:consider|take) the statement: (.+?)\./i)
      if (stated === null) return null
      const fact = parseLogicFact(stated[1] ?? '')
      if (fact === null) return null
      return tSym('bool.not', [fact])
    }
    case 'logic-if': {
      const sentences = prompt.split('. ').map((sentence) => sentence.replace(/[.?]\s*$/, '').trim())
      const conditional = sentences[0]?.match(/^if (.+), then (.+)$/i)
      if (conditional === null) return null
      const condition = conditional[1] ?? ''
      const consequence = conditional[2] ?? ''
      const statement = sentences[1]
      if (statement === undefined) return null
      const c = phrase(condition)
      const q = phrase(consequence)
      const imp = tSym('imp', [c, q])
      // The third clause is the premise: an affirmed condition (modus
      // ponens) or a denied consequence (modus tollens).
      if (/\bnot\b/i.test(statement) || /^no\b/i.test(statement)) {
        return tSym('logic.mt', [imp, tSym('nq', [q])])
      }
      return tSym('logic.mp', [imp, c])
    }
    case 'syllogism': {
      const m = prompt
        .trim()
        .match(/^all (.+) are (.+)\. (.+) is (.+)\. (?:is|must) ([a-z]+)(?: be)? ([a-z ]+)\??$/i)
      if (m === null) return null
      const members = m[1] ?? ''
      const category = m[2] ?? ''
      const name = m[3] ?? ''
      const member = m[4] ?? ''
      const object = m[6] ?? ''
      // Both phrases use the lifted singular so the repeated-variable
      // equality in the rule patterns resolves ('cats' vs 'a cat' -> 'cat').
      const all = tSym('all', [phrase(lifted(members)), phrase(lifted(category))])
      const isa = tSym('isa', [phrase(name), phrase(lifted(member))])
      if (lifted(object) === lifted(category)) {
        return tSym('logic.barbara', [all, isa])
      }
      return tSym('logic.affirmed', [all, isa])
    }
    default:
      return null
  }
}
